### ISSUE TITLE
Deprecation messages

### ISSUE THREAD

**Issue by DieterHolvoet** [springload/react-simpler-select#25]
My console is printing these errors:
`Warning: Select: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Coming from the following file:
`react-simpler-select/lib/components/Select.js`

**Comment by thibaudcolas** [comment]
Thanks for the report @DieterHolvoet, this is because this component hasn't been migrated to support React 15.5 and above yet.

We will get to it when we need it (the component still works the same, it's just a warning), if you need this soon could you make a pull request with the upgrade? I'm more than happy to help you along the way if you're up for it.

**Comment by DieterHolvoet** [comment]
I made a pull request: https://github.com/springload/react-simpler-select/pull/26

**Comment by thibaudcolas** [comment]
👍 will proceed there.
